name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      # Train model and generate artefacts
      - name: Train Model
        run: pipenv run python model_api.py tune

      - name: Run Unit Tests
        run: pipenv run pytest tests/

  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3

      # Authenticate to Google Cloud using Workload Identity
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/mlops-house-predict/locations/global/workloadIdentityPools/house-price-pool/providers/house-price-pool-provider"
          service_account: "house-price-demo@mlops-house-predict.iam.gserviceaccount.com"

      # Build and push Docker image to GCR
      - name: Build and Push to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
          registry: gcr.io
          project_id: "mlops-house-predict"
          image_name: "mlops_house_price_predict"
          image_tag: latest,v1
          dockerfile: "./Dockerfile"
          context: "."

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deploy.yaml
