name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      # Train model and generate artefacts
      - name: Train Model
        run: pipenv run python model_api.py tune

      - name: Run Unit Tests
        run: pipenv run pytest tests/

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Set this in GitHub secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Set this in GitHub secrets

      # Set up Google Cloud SDK with service account authentication
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      # Build Docker Image
      - name: Build Docker Image
        env:
          IMAGE_NAME: mlops_house_price_predict
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        run: |-
          docker build -t andy237/$IMAGE_NAME .
          docker build -t us.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest .

      # Configure Docker Client for GCR
      - name: Configure Docker Client for GCR
        run: gcloud auth configure-docker --quiet

      # Push Docker Image to Docker Hub and GCR
      - name: Push Docker Image to Docker Hub and GCR
        env:
          IMAGE_NAME: mlops_house_price_predict
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        run: |-
          docker push andy237/$IMAGE_NAME
          docker tag andy237/$IMAGE_NAME:latest us.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push us.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      # Extract metadata (tags, labels) for Docker GHCR
      - name: Extract metadata for GHCR
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image to GHCR
      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Authenticate kubectl with GKE
      - name: Set up Kubeconfig for GKE
        run: |
          gcloud container clusters get-credentials house-price --zone us-central1-c --project ${{ secrets.GCP_PROJECT }}

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deploy.yaml
